const wine = [
    {
        name:'Terra Malbec',
        img:'www.espaciovino.com.ar/media/default/0001/63/thumb_62806_default_small.jpeg',
        description:'80% del vino es estacionado durante 6 meses en barricas de roble francés y americano, y el restante 20% en tanques de acero inoxidable para preservar la frescura del vino. Luego permanece en botella durante 6 meses antes de su expendio.',
        type:'Tinto',
        varietal:'Malbec',
        bodega:'Viniterra',
        precio: 432,
        stock:30,
        category:wine,
    },
    {
        name:'Postales Del Fin Del Mundo',
        img:"www.espaciovino.com.ar/media/default/0001/64/thumb_63323_default_big.jpeg",
        description:'6 meses en roble francés y americano',
        type:'Tinto',
        varietal:'Malbec',
        bodega:'Del Fin Del Mundo',
        precio: 540,
        stock:30,
        category:wine,
    },
    {
        name:'Dv Catena Cabernet Malbec ',
        img:"www.espaciovino.com.ar/media/default/0001/53/thumb_52791_default_big.jpeg",
        description:'DV Catena Cabernet Sauvignon-Malbec es un vino elegante y complejo, de color rojo rubi con reflejos violetas.A la nariz, intenso y concentrado, presenta notas de especias aportadas por el Cabernet Sauvignon del viñedo La Pirámide, y notas de moras maduras y ciruelas, características del Malbec del viñedo Angélica, acompañadas por vainilla, tabaco y licor aportadas por la crianza en roble.En boca, de impacto dulce y gran complejidad, con taninos integrados y redondos, de final largo y persistente.',
        type:'Tinto',
        varietal:'Blend',
        bodega:'Catena Zapata',
        precio: 1.500,
        stock:30,
        category:wine,
    },
    {
        name:'Del Fin Del Mundo Special Blend',
        img:"www.espaciovino.com.ar/media/default/0001/55/thumb_54326_default_big.jpeg",
        description:'Color rojo profundo, muy intenso.Aroma potente recuerda a frutos rojos, especias y mermelada de frutas, notas a nuez de coco, ahumado y tabaco.En boca es frutado, delicado, de exquisito equilibrio, con taninos suaves y redondos. Su final de boca es elegante y prolongado. Vino de gran jerarquía.',
        type:'Tinto',
        varietal:'Blend',
        bodega:'Del Fin del Mundo',
        precio: 3.870,
        stock:30,
        category:wine,
    },
    {
        name:'Quara Reserva Cabeernet Sauvignon',
        img:"www.espaciovino.com.ar/media/default/0001/59/thumb_58415_default_big.jpeg",
        description:'De color rojo rubí, intenso y de buen matiz.En nariz, muy frutado y expresivo, con notas de pimientos y pimientas típicos de ese terroir.De buena estructura en boca, voluminoso, con taninos intensos y muy maduros. De final largo y aromático, con notas complejas de vainilla y tostado, aportadas por su paso por madera.',
        type:'Tinto',
        varietal:'Cabernet Sauvignon',
        bodega:'Finca Quara',
        precio: 410,
        stock:30,
        category:wine,
    },
    {
        name:'Famiglia Bianchi Cabernet Sauvignon',
        img:"www.espaciovino.com.ar/media/default/0001/53/thumb_52940_default_big.jpeg",
        description:'Vino de color rojo rubí intenso y muy buena lágrima.Vino de una elegancia y personalidad destacada, sus aromas especiados seducen por su complejidad e intensidad. Pimienta negra, regaliz, cedro, granos de café tostados y dejos de menta fresca se arremolinan alrededor de frutadas sensaciones de cassis, moras y frutos silvestres.En boca se expresa ampliamente con gran persistencia de aromas y una notable y armoniosa estructura que acentúan su linaje real.',
        type:'Tinto',
        varietal:'Cabernet Sauvignon',
        bodega:'Casa Bianchi',
        precio: 810,
        stock:30,
        category:wine,
    },
    {
        name:'Pulenta Estate Merlot',
        img:"www.espaciovino.com.ar/media/default/0001/55/thumb_54228_default_big.jpeg",
        description:'Estas notables variaciones de temperatura entre el día y la noche, llevan a nuestros viñedos a lograr colores muy profundos, con caracteres frutados muy intensos, aquí, la cereza, el eucalipto, y la menta emergen, para combinarse con las excelentes notas de madera. su gran estructura y persistencia en boca hacen de éste un gran vino.',
        type:'Tinto',
        varietal:'Merlot',
        bodega:'Pulenta Estate',
        precio: 1.750,
        stock:30,
        category:wine,
    },
    {
        name:'Casa Boher Merlot',
        img:"www.espaciovino.com.ar/media/default/0001/56/thumb_55354_default_big.jpeg",
        description:'Vista:A la vista presenta un color rojo rubí muy intenso con tintes violáceos.Nariz:El aroma de este vino refleja la prolongada maduración de sus bayas donde se perciben frutas secas, guindado, suave pimiento dulce y cassis.Boca: A la boca tiene taninos suaves y buena estructura. Su contenido alcohólico da sensación de dulzura. Con sabores a ciruela y pasas de uva',
        type:'Tinto',
        varietal:'Merlot',
        bodega:'Rosell Boher',
        precio: 1.100,
        stock:30,
        category:wine,
    },
    {
        name:'Sacacorcho 2 tiempos Azul WineFroz',
        img:"www.espaciovino.com.ar/media/default/0001/56/thumb_55299_default_big.jpeg",
        description:'Sacacorcho 2 Tiempos en Color Azul',
        type:null,
        varietal:null,
        bodega:null,
        precio: 550,
        stock:30,
        category:accessories,
    },
    {
        name:'Sacacorcho Caucho Winefroz',
        img:"www.espaciovino.com.ar/media/default/0001/56/thumb_55288_default_big.jpeg",
        description:'Peso: Peso bruto 0,3kg Medidas: Ancho 5 cm - Alto 26 cm - Profundidad 5 cm Medidas con caja: Ancho 10,5 cm - Alto 28 cm - Profundidad 9,5 cm Pilas: el modelo funciona con 4 Pilas AA (no incluye las mismas).',
        type:null,
        varietal:null,
        bodega:null,
        precio: 4.150,
        stock:30,
        category:accessories,
    },
    {
        name:'Sacacorcho Acero Winefroz',
        img:"www.espaciovino.com.ar/media/default/0001/56/thumb_55287_default_big.jpeg",
        description:'Peso: Peso bruto 0,4kg Medidas: Ancho 5 cm - Alto 27 cm - Profundidad 5 cm Medidas con caja: Ancho 10,5 cm - Alto 32,5 cm - Profundidad 9 cm Pilas: el modelo funciona con 4 Pilas AA (no incluye las mismas).',
        type:null,
        varietal:null,
        bodega:null,
        precio: 4.150,
        stock:30,
        category:accessories,
    },
    {
        name:'Aireador de Vino Winefroz',
        img:"www.espaciovino.com.ar/media/default/0001/56/thumb_55294_default_big.jpeg",
        description:'Verte el vino en forma uniforme y pausada de manera que entra en contacto con la máxima superficie de aire posible antes de entrar en la copa.',
        type:null,
        varietal:null,
        bodega:null,
        precio: 4.999,
        stock:30,
        category:accessories,
    },
    {
        name:'Limpia Copa + Limpia Decanter Winefroz',
        img:"www.espaciovino.com.ar/media/default/0001/56/thumb_55292_default_big.jpeg",
        description:'Set de accesorios Winefroz que contiene: un (1) Limpia Copa y un (1) Limpia Decanter.',
        type:null,
        varietal:null,
        bodega:null,
        precio: 2.150,
        stock:30,
        category:accessories,
    },
    {
        name:'Copa Bordeaux Linea Wine Lovers ',
        img:"www.espaciovino.com.ar/media/default/0001/54/thumb_53348_default_big.jpeg",
        description:'Altura: 226 mm. (8 8/9 inch),Capacidad: 580 ml. (20 1/2 oz),Diámetro: 92 mm. (3 5/8 inch)',
        type:null,
        varietal:null,
        bodega:null,
        precio: 1375,
        stock:30,
        category:accessories,
    },
    {
        name:'Copa Vino Blanco Linea Wine Lovers ',
        img:"www.espaciovino.com.ar/media/default/0001/54/thumb_53349_default_big.jpeg",
        description:'Altura: 209 mm. (8 2/9 inch),Capacidad: 380 ml. (13 2/5 oz),Diámetro: 80 mm. (3 1/7 inch)',
        type:null,
        varietal:null,
        bodega:null,
        precio: 1375,
        stock:30,
        category:accessories,
    },
    {
        name:'Decanter Casual',
        img:"www.espaciovino.com.ar/media/default/0001/62/thumb_61387_default_big.jpeg",
        description:'Alto: 240 mm,Capacidad: 1400 ml,Boca: 135 mm.',
        type:null,
        varietal:null,
        bodega:null,
        precio: 6.930,
        stock:30,
        category:accessories,
    },
    {
        name:'Decanter Hybrid',
        img:"www.espaciovino.com.ar/media/default/0001/62/thumb_61388_default_big.jpeg",
        description:'Alto: 270 mm,Capacidad: 1800 ml,Boca: 164 mm.',
        type:null,
        varietal:null,
        bodega:null,
        precio: 12.400,
        stock:30,
        category:accessories,
    },
]


